env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
globals:
  allure: readonly
  browser: readonly
  by: readonly
  jasmine: readonly
  describe: readonly
  xdescribe: readonly
  beforeAll: readonly
  afterAll: readonly
  beforeEach: readonly
  it: readonly
  xit: readonly
  expect: readonly
  logger: readonly
  screenShotUtils: readonly
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  max-len: [2, {"code": 150, "ignoreUrls": true, "ignoreStrings": true}]
  class-methods-use-this: [2, { "exceptMethods": ['schema'] }]